### ISSUE TITLE
Auto-generate VERSION file

### ISSUE THREAD

**Issue by elidupuis** [sethwebster/ember-cli-new-version#10]
Any interest in this addon having an option to automatically generating the `VERSION.txt` file during the build process? I have something similar in an app that uses the `treeForPublic` addon hook to create a `version` file in the `public/` directory.

**Comment by sethwebster** [comment]
Feel free to send a PR for everyone to check out :)

**Comment by sethwebster** [comment]
Hey @elidupuis -- any time/luck?

**Comment by elidupuis** [comment]
@sethwebster Haven't had time to dig into it but I'll try to take a look in the next couple of days. Thanks for pinging :wink:

**Comment by sethwebster** [comment]
Closed in #11, commit e87c522. Thanks @elidupuis!
