### ISSUE TITLE
No automatic version in v3 with ember-cli-app-version?

### ISSUE THREAD

**Issue by jrjohnson** [sethwebster/ember-cli-new-version#103]
With v3 my app always shows that there is a new version. It appears that [Users of the addon must set currentVersion](https://github.com/sethwebster/ember-cli-new-version/blob/2b6c3155fdda1c6c2d57f233799330ab3e5c2e6b/addon/services/new-version.js#L52-L55) requires setting a version in `config/environment.js`. 

Can this addon pull that data from ember-cli-app-version when `useAppVersion` is enabled? Otherwise I'm not sure how to configure this initial version value.

**Comment by knownasilya** [comment]
@pbernery can you comment on this?

**Comment by knownasilya** [comment]
@jrjohnson I think that would be a reasonable approach.

**Comment by knownasilya** [comment]
@jrjohnson did you try https://github.com/sethwebster/ember-cli-new-version#automatic-version-file-creation ?

**Comment by jrjohnson** [comment]
Yes, I should have included that, but we have:
```
newVersion: {
    enabled: true,
    useAppVersion: true
  }
``` in our config.

**Comment by vst** [comment]
I am experiencing the same issue. Can I assume that the `ember-cli-app-version` support is broken?

**Comment by knownasilya** [comment]
It would seem so. Feel free to bisect and submit a PR. I probably can't get to it until tomorrow at the earliest.

**Comment by jrjohnson** [comment]
I dug into this yesterday. The issue is that `useAppVersion: true` is set in `ember-cli-build.js` and there isn't a way to read that value in the service or in the `config` hook in `index.js`. If someone knows of a way to do that this is a quick fix. Otherwise we'll need another breaking change and will need to:
1) Remove this config option, if `ember-cli-app-version` is present and now `version` is set in `config/environment.js` then the version from `ember-cli-app-version` is used automatically.
2) Move  the `useAppVersion` option to `config/environment.js`.
3) Combine these two. Move the value to `environment.js`, but default it to `true`.

I prefer option 3 myself, the original addition of this feature wasn't written this way to avoid a BC break, but since that break seems unavoidable now I think we should go this route.

Alternatively maybe this is a bug fix? In that case option 2 is probably justifiably a fix and not a breaking change.

Thoughts @knownasilya? I can get a PR together today if one of these appeals to you.

**Comment by oleg-andreyev** [comment]
It looks like simple issue
![image](https://user-images.githubusercontent.com/1244112/144577325-af73c34b-a8c3-48ce-92b4-1a775f557df6.png)

When service is loaded you have access to APP.version.

**Comment by jrjohnson** [comment]
Agreed @oleg-andreyev, but you don't have access to the 'useAppVersion' option which is currently set in 'ember-cli-build.js'.

**Comment by knownasilya** [comment]
@jrjohnson does this change your approach? Can probably just fix that getter and release it as bug fix

**Comment by jrjohnson** [comment]
I don't see how we can since `useAppVersion` currently defaults to false. If we use that value in the getter without checking this value that seems like a breaking change to me. Thinking about it some more I'm incline to remove the `useAppVersion` option from config. If you have `ember-cli-app-version` installed and you *do not* have a `currentVersion` set in `config/environment.js` I think we should use that version. This removes some complexity, but is still a breaking change.

**Comment by jrjohnson** [comment]
Actually there are conflicts between the service and the auto file creation even without `ember-cli-app-version`. I think a BC break is probably unavoidable, however it shouldn't be a big deal because app authors probably don't need to do anything in most cases other than possibly moving config. I'll get a PR together today or tomorrow to:
1) Document the config expected in the service
2) Move `enabled` and `useAppVersion` to `config/environment.js` an out of `ember-cli-build.js`
3) Use the version in `package.json` for both the generated `VERSION.txt` and the `currentVersion` options unless `currentVersion` is set in config.

**Comment by jrjohnson** [comment]
Would appreciate some eyes on #104 from apps other than my own to check if I'm wrong about sensible defaults and what needs to be configurable vs what can be assumed.

**Comment by basz** [comment]
for those who need a quick fix

I create an initializer thats seems to work

/initializers/environment.js
``` 
import ENV from '@plhw-lab/lab-plhw/config/environment';

export function initialize() {
    ENV.newVersion = Object.assign(ENV?.newVersion || {}, { currentVersion: ENV.APP.version });
}

export default {
  name: 'environment',
  initialize,
};
```

**Comment by knownasilya** [comment]
Thanks for the reminder 😄

**Comment by knownasilya** [comment]
v4 is out
