### ISSUE TITLE
In development, banner is not dismissible

### ISSUE THREAD

**Issue by kategengler** [sethwebster/ember-cli-new-version#116]
In development, using ember-cli-app-version, the banner is not dismissible because VERSION.txt is not regenerated upon commit.

**Comment by knownasilya** [comment]
@kategengler #117 was released in v4.1.0. Let me know if that helps.

**Comment by yusufsagdic** [comment]
Also currentVersion not using ember-cli-app-version, its came up null.

Since version 4.0.0 this addons will use the version string provided by [ember-cli-app-version](https://github.com/ember-cli/ember-cli-app-version) if no currentVersion is configured.

**Comment by knownasilya** [comment]
@yusufsagdic does https://github.com/sethwebster/ember-cli-new-version/pull/104 help?

**Comment by yusufsagdic** [comment]
@knownasilya yes, thanks.
