### ISSUE TITLE
Embroider - Cannot destructure property `currentVersion` of `this._config`

### ISSUE THREAD

**Issue by pkimber** [sethwebster/ember-cli-new-version#119]
I get the following error while building with Embroider:
```
Building into /tmp/embroider/f8be1a
Created VERSION.txt with 0.0.1+710f3f65
Cannot destructure property 'currentVersion' of 'this._config' as it is undefined.
```
I guess this is from [new-version.js](https://github.com/sethwebster/ember-cli-new-version/blob/master/addon/services/new-version.js)

**Comment by knownasilya** [comment]
Embroider should still support all Ember APIs, including `return getOwner(this).resolveRegistration('config:environment')`.
Does the project have a `config/environment.js` and is it exporting an object?

**Comment by knownasilya** [comment]
Which version are you on? 4.1.0?

**Comment by pkimber** [comment]
Yes, version 4.1.0.  Your comment pointed me in the right direction.  Moving:
```
    "ember-cli-new-version": "^4.1.0",
```
from `dependencies` to `devDependencies` in my add-on solved the issue.  I guess the project was looking in the addon for the export?

Thank you for your help :)
