### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by medokin** [sethwebster/ember-cli-new-version#18]
- [x] Replace `setTimeout` with `Ember.run`, Obsolete. Using ember-concurrency.
- [x] Clear Timeout when object gets destroyed #16 
- [x] change comparision
- [x] Update to current ember-cli version
- [x] Add real tests #29
- [x] Use https://github.com/ember-cli/ember-ajax

**Comment by sethwebster** [comment]
Thanks, Medokin.

ClearTimeout is taken care of in #16 
Feel free to submit PRs on others (please squash)

Thanks!

**Comment by medokin** [comment]
Sure, what do you think about dropping version number comparison and instead just check whether they differ.

The point is, what if you are rolling out a downgrade because something went wrong before.

**Comment by sethwebster** [comment]
Probably makes sense with perhaps customized messaging? One for up and one for down? Thoughts @knownasilya @elidupuis @jakesjews @jsec ?

**Comment by medokin** [comment]
I think version comparision by number should not be part of this addon. No matter if up or down. If the user wants to show different messages on update/downgrade he should build his own version check.

It should just check `currentVersion != newVersion` and show the component.

If you'll accept I can make the changes by monday. It would be a minor change.

**Comment by jsec** [comment]
I'm inclined to agree with @medokin. The thought also occurred that defaulting into announcing a downgrade might cause an issue for some people. Exposing the versions and letting developers opt into up/down messaging if they wish should be sufficient.

**Comment by sethwebster** [comment]
Agree @jsec. @medokin -- go for it.

**Comment by medokin** [comment]
Here my thoughts for the next steps:
- Update to current stable ember-cli
- Extract version check into a service to allow custom checks and easy testing
- Add tests (patch)
  - Test component with mocked service
  - Test service with mirage
  - ember-try builds
- Replace setTimeout with Ember.run (patch)
- Use https://github.com/ember-cli/ember-ajax

**Comment by sethwebster** [comment]
#19 Merged

**Comment by medokin** [comment]
@sethwebster some thoughts about https://github.com/sethwebster/ember-cli-new-version/issues/18#issuecomment-221218040 ? I'm ready to implement... Waiting for your go.

**Comment by sethwebster** [comment]
@medokin - sounds great. Thanks for contributing again!

**Comment by sethwebster** [comment]
How's it going, @medokin ?

**Comment by medokin** [comment]
Well, ended up in 80% rewrite. I'll push it next week for first review..

**Comment by sethwebster** [comment]
@medokin -- can you check and see how this lines up with where we are now?

**Comment by medokin** [comment]
@sethwebster Well nothing has changed since i had this service based architecture idea https://github.com/sethwebster/ember-cli-new-version/pull/21#issuecomment-236842440

Depends on you, does it make sense to rewrite or leave it as it is and fix the points above https://github.com/sethwebster/ember-cli-new-version/issues/18#issue-154189062

**Comment by knownasilya** [comment]
I'd just do #18, which should probably be split out into separate issues.

**Comment by sethwebster** [comment]
Agreed.

**Comment by medokin** [comment]
Alright 👍  I think missing tests is the blocking issue for further contributions and should be fixed first.

**Comment by sethwebster** [comment]
Updated ember-cli

**Comment by medokin** [comment]
I think this is all done.

**Comment by sethwebster** [comment]
Sweet.
