### ISSUE TITLE
Default interval too short

### ISSUE THREAD

**Issue by knownasilya** [sethwebster/ember-cli-new-version#2]
5 seconds seems like a bit much.
I'd default to something like every 5 minutes (`300000`), since deploys don't
happen that often, and doing an ajax request that often will just eat the user's bandwidth (small, but it adds up).

**Comment by sethwebster** [comment]
Thanks for the note! Obviously, you can override this easily; for the use-case it was created, an application with tons of single-page data entry, and it's currently being rapidly improved (multiple deploys per day), it makes sense. We didn't want people to enter a bunch of data and only to find out the api changed.

5s may be too short for general use. Maybe a fair compromise is 1m? Love to hear from others.

**Comment by knownasilya** [comment]
1 minute sounds better. I'll take that compromise.

**Comment by sethwebster** [comment]
Closed in PR #3
