### ISSUE TITLE
Globalization for reload button

### ISSUE THREAD

**Issue by shijistar** [sethwebster/ember-cli-new-version#22]
Please add a property for configuring the text of reload button, we don't provide English version as default.

**Comment by sethwebster** [comment]
Feel free to submit a PR

**Comment by sethwebster** [comment]
Closed by mistake.

**Comment by sethwebster** [comment]
@shijistar -- do you want to add this enhancement?

**Comment by knownasilya** [comment]
@shijistar this is currently possible by reimplementing the html in the notification, for example I do the following in one of my apps:

```hbs
{{#new-version-notifier versionFileName='/version' updateInterval=updateInterval as |version lastVersion reload close|}}
  <div id="toast-container" class="new-version-notification toast-bottom-left">
    <div class="toast toast-info">
      <button type="button" class="toast-close-button" role="button" onclick={{action close}}>×</button>
      <div class="toast-message">
        <p> 
          A new version (v{{version}}) of MapGeo is available
        </p>
        <button type="button" class="btn btn-default btn-block" onclick={{action reload}}>
          Reload to Update
        </button>
      </div>
    </div>
  </div>
{{/new-version-notifier}}
```

**Comment by shijistar** [comment]
Yes, I'm doing like your suggestion, but the default template is ok for me, just want to change the reload button text. I created a new PR, https://github.com/sethwebster/ember-cli-new-version/pull/31
