### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jakesjews** [sethwebster/ember-cli-new-version#24]
Would it be possible to get a release published with the changes from https://github.com/sethwebster/ember-cli-new-version/pull/19?

**Comment by sethwebster** [comment]
Apologies - I've been traveling.  I'll take a look soon.

**Comment by knownasilya** [comment]
Along with https://github.com/sethwebster/ember-cli-new-version/pull/25

**Comment by sethwebster** [comment]
Thanks, @knownasilya.

**Comment by sethwebster** [comment]
Do you know your npmjs id?

**Comment by knownasilya** [comment]
Same as here, `knownasilya`

**Comment by sethwebster** [comment]
Apparently it's case sensitive there. Added.
