### ISSUE TITLE
Overriding `this.options.babel` no longer supported

### ISSUE THREAD

**Issue by polarctos** [sethwebster/ember-cli-new-version#33]
During Ember builds the following deprecation is shown:

```[INFO] DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-cli-new-version` (found at `(...)\node_modules\ember-cli-new-version`) has overridden the `this.options.babel` options which conflicts with the addons ability to transpile its `addon/` files properly. Falling back to default babel configuration options.```

Ember CLI: v2.12.1
ember-cli-new-version: v1.0.8

**Comment by devotox** [comment]
Is this project still actively maintained?

**Comment by sethwebster** [comment]
Yes

**Comment by devotox** [comment]
Thank you @sethwebster will the deprecations be handled in an upcoming release?
