### ISSUE TITLE
missing ember-concurrency when using version 1.1.4

### ISSUE THREAD

**Issue by initram** [sethwebster/ember-cli-new-version#37]
After upgrading from version 1.1.1 to version 1.1.4, we are getting the following message when browsing to the site:

> Could not find module `ember-concurrency` imported from `ember-cli-new-version/components/new-version-notifier/component`

It seems that ember-concurrency have not been added as a dependency, even though it is used after development.

**Comment by knownasilya** [comment]
Will post here once we've published a new version.

**Comment by knownasilya** [comment]
1.1.5 released
