### ISSUE TITLE
How am I supposed to write acceptance tests for apps that use this addon?

### ISSUE THREAD

**Issue by initram** [sethwebster/ember-cli-new-version#38]
When I try to run my acceptance tests using the latest version (1.1.5) then they timeout on visit calls as the test waits for all promises to resolve. 

Is there a way to disable version polling during testing? (I don't really care about testing that part of my app)

What do other people do that use this addon? are there any examples of acceptance tests from "real" apps that use this addon?

**Comment by bgentry** [comment]
As I noted in #43, this becomes an issue if you customize the `updateInterval` to a non-default value. #47 resolves that and I think also improves the testing story a bunch by making the addon just not do any version checks in tests by default.

**Comment by initram** [comment]
Sounds great! looking forward to a version released with these changes.

**Comment by initram** [comment]
After upgrading to the latest version I no longer have issues with running my integration tests.
