### ISSUE TITLE
CI not working

### ISSUE THREAD

**Issue by bgentry** [sethwebster/ember-cli-new-version#48]
Maybe it needs to be toggled on the Travis CI side?

**Comment by knownasilya** [comment]
As far as I can tell it's on, but maybe it's off on the Github side. I don't have access to the settings.

**Comment by bgentry** [comment]
Right, we probably need @sethwebster’s help to reactivate it or would have to move the repo to another account.

**Comment by knownasilya** [comment]
Ping @sethwebster

**Comment by sethwebster** [comment]
Pong. Checking.

**Comment by sethwebster** [comment]
@bgentry / @knownasilya -- just triggered a build by updating the README. Can you tell me more about what's not working?

**Comment by bgentry** [comment]
Well, those appear to be the first builds to have run in awhile: https://travis-ci.org/sethwebster/ember-cli-new-version/builds

I think at the time they weren't running. Now they appear to be running but partially broken :)

**Comment by sethwebster** [comment]
Yeah, one of the specs is failing for a specific ember version. I've at least finally returned to development :) I was traveling doing innovation consulting for the last few years. Sadly, I'm not doing any ember dev anymore so help is appreciated...

**Comment by knownasilya** [comment]
I'll try and have a look this week.
