### ISSUE TITLE
Cannot read property 'browsers' of undefined

### ISSUE THREAD

**Issue by jayarnielsen** [sethwebster/ember-cli-new-version#55]
After upgrading to v1.4.2, I can't run my development server any more. It crashes with the following error when attempting to start:

`Cannot read property 'browsers' of undefined`

The app is running on ember 3.4.4

**Comment by knownasilya** [comment]
Is there a stack trace?

**Comment by knownasilya** [comment]
In the new version we use ember-fetch, which seems to read the apps browser targets (https://github.com/ember-cli/ember-fetch/blob/029cc6f83fd9bd090890e2374f444edc3f77a98f/index.js#L80).

Do you have targets defined in your app? Something like https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/targets.js

**Comment by jayarnielsen** [comment]
Here's what I've got, definitely seems to be related to ember-fetch:

```
ERROR Summary:

- broccoliBuilderErrorStack: [undefined]
- codeFrame: [undefined]
- errorMessage: Cannot read property 'browsers' of undefined
- errorType: [undefined]
- location:
  - column: [undefined]
  - file: [undefined]
  - line: [undefined]
- message: Cannot read property 'browsers' of undefined
- name: TypeError
- nodeAnnotation: [undefined]
- nodeName: [undefined]
- originalErrorMessage: [undefined]
- stack: TypeError: Cannot read property 'browsers' of undefined
  at Class.treeForBrowserFetch (/ember-client/node_modules/ember-fetch/index.js:154:30)
  at Class.treeForVendor (/ember-client/node_modules/ember-fetch/index.js:111:28)
  at Class._treeFor (/ember-client/node_modules/ember-cli/lib/models/addon.js:617:33)
  at Class.treeFor (/ember-client/node_modules/ember-cli/lib/models/addon.js:577:21)
  at addons.reduce (/ember-client/node_modules/ember-cli/lib/models/addon.js:450:26)
  at Array.reduce (<anonymous>)
  at Class.eachAddonInvoke (/ember-client/node_modules/ember-cli/lib/models/addon.js:447:24)
  at Class.treeFor (/ember-client/node_modules/ember-cli/lib/models/addon.js:576:22)
  at project.addons.reduce (/ember-client/node_modules/ember-cli/lib/broccoli/ember-app.js:698:26)
  at Array.reduce (<anonymous>)
```

I do have a targets.js file with the following:

```javascript
'use strict';

const browsers = [
  '> 1% in US',
  'last 3 versions',
  'last 5 Chrome versions',
  'Firefox ESR',
  'ie >= 10'
];

const isCI = !!process.env.CI;
const isProduction = process.env.EMBER_ENV === 'production';

if (isCI || isProduction) {
  browsers.push('ie 11');
}

module.exports = {
  browsers
};
```

**Comment by knownasilya** [comment]
Hum, it looks to be their internal config object used here: https://github.com/ember-cli/ember-fetch/blob/master/index.js#L111

But it is only defined in `included` here: https://github.com/ember-cli/ember-fetch/blob/master/index.js#L77

The comment says `included` runs at the very beginning, so not sure what's going on there.

**Comment by knownasilya** [comment]
@jayarnielsen give 1.4.3 a try, make sure to run `ember g ember-cli-new-version` or install with `ember install ember-cli-new-version`.

**Comment by jayarnielsen** [comment]
Now it's working, thank you!
