### ISSUE TITLE
Have you considered moving fetch and logic to a service?

### ISSUE THREAD

**Issue by pbernery** [sethwebster/ember-cli-new-version#93]
I like this addon and consider using it in my app, however I'd like to automatically refresh the app in some conditions, so that the user does not have to think about refreshing the app.

For this purpose, having the fetch of version.txt and the logic in a service would make sense, and let the component just show when the service detects a new version.

I saw there were some short discussions about this in https://github.com/sethwebster/ember-cli-new-version/issues/18 and it has been set aside at that time.

Do you believe it would make sense to move the code in a service now? I may do the work if you believe it is. I saw you started a migration to [Octane](https://github.com/sethwebster/ember-cli-new-version/pull/91), I guess I'd start from this PR in that case.

**Comment by knownasilya** [comment]
I think it would be the right approach, and totally for merging a PR of that nature.

**Comment by pbernery** [comment]
Nice, great to read that.
I'll try to work something out in the next days.

**Comment by pbernery** [comment]
Here is a first proposition of this split https://github.com/sethwebster/ember-cli-new-version/pull/94.
It has breaking changes, so this may be to be discussed.
